global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'webhook'
    static_configs:
      - targets: ['webhook:5000']
        labels:
          service: 'webhook'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
